api = "0.2"

[buildpack]
  id = "paketo-community/rackup"
  name = "Rackup Buildpack"

[[stacks]]
  id = "org.cloudfoundry.stacks.cflinuxfs3"

[metadata]
  include_files = ["bin/run", "bin/build","bin/detect","buildpack.toml"]
  pre_package = "./scripts/build.sh"
